version: "3.3"
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
      - "443:443"
    networks:
      - front-tier
      - back-tier
      - phpmyadmin-tier
    # configs:
    #   - httpd-config
    # secrets:
    #   - server-certificate
    
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8050:80"
    networks:
      - front-tier
      - back-tier
      - phpmyadmin-tier
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST : backend
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: Denver26
    depends_on:
      - backend
    links:
      - backend:mysql
    volumes:
      - db-data:/etc/data

  backend:
    image: mariadb
    volumes:
      - db-data:/etc/data
    networks:
      - back-tier
    environment:
      - MYSQL_ROOT_PASSWORD=Denver26
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
      - MYSQL_DATABASE=wordpress

volumes:
  db-data:

configs:
  httpd-config:
    external: true

# secrets:
#   server-certificate:
#     external: true

networks:
  # The presence of these objects is sufficient to define them
  front-tier: 
    driver: bridge
  back-tier: 
    driver: bridge
    internal: true
  phpmyadmin-tier: 
    driver: bridge
