version: '3'
services:
  frontend:
    image: aboudevops/wordpress-netdata:v0.1.0
    pid: host
    restart: unless-stopped
    ports:
      - "8080:80"
      - "80:19999"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - front-tier
      - back-tier
      - phpmyadmin-tier
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8050:80"
    networks:
      - front-tier
      - back-tier
      - phpmyadmin-tier
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: backend
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: Denver26
    depends_on:
      - backend
    links:
      - backend:mysql
    volumes:
      - db-data:/etc/data

  backend:
    image: mariadb
    volumes:
      - db-data:/etc/data
    networks:
      - back-tier
    environment:
     environment:
      - MYSQL_ROOT_PASSWORD=Denver26
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
      - MYSQL_DATABASE=wordpress

volumes:
    db-data:
    netdataconfig:
    netdatalib:
    netdatacache:

networks:
  # The presence of these objects is sufficient to define them
  front-tier: 
    driver: overlay
  back-tier: 
    driver: overlay
    internal: true
  phpmyadmin-tier: 
    driver: overlay
